"""empty message

Revision ID: c85a14ed5561
Revises: 075afcd358e8
Create Date: 2023-11-09 14:52:48.644919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85a14ed5561'
down_revision = '075afcd358e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_submission',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('refactoring_status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('refactoring_statistics',
    sa.Column('static_id', sa.Integer(), nullable=False),
    sa.Column('total_reduction', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('static_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refactoring_statistics')
    op.drop_table('code_submission')
    # ### end Alembic commands ###
