"""empty message

Revision ID: 14a6da595d64
Revises: 95c3a29f15b7
Create Date: 2023-11-16 11:17:14.268414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14a6da595d64'
down_revision = '95c3a29f15b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitted_code',
    sa.Column('submission_id', sa.String(length=100), nullable=False),
    sa.Column('submission_date', sa.Time(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.drop_table('code_submission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_submission',
    sa.Column('submission_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('submission_date', mysql.TIME(), nullable=False),
    sa.Column('code', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('submission_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('submitted_code')
    # ### end Alembic commands ###
