"""Initial migration.

Revision ID: 531cb13e2260
Revises: 31cd0b6a8bcd
Create Date: 2023-11-12 14:37:31.613048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531cb13e2260'
down_revision = '31cd0b6a8bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_submission',
    sa.Column('submission_id', sa.String(length=100), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('refactoring_statistics',
    sa.Column('static_id', sa.Integer(), nullable=False),
    sa.Column('refactoring_date', sa.Date(), nullable=False),
    sa.Column('reduction_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('static_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refactoring_statistics')
    op.drop_table('code_submission')
    # ### end Alembic commands ###
