"""empty message

Revision ID: 7e41afb458c9
Revises: 531cb13e2260
Create Date: 2023-11-15 12:55:39.518369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e41afb458c9'
down_revision = '531cb13e2260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_submission', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
