"""empty message

Revision ID: 9fdd2206b5d6
Revises: b0ef92b8e9a0
Create Date: 2023-11-15 13:41:48.164992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdd2206b5d6'
down_revision = 'b0ef92b8e9a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_submission', schema=None) as batch_op:
        batch_op.alter_column('submission_date',
               existing_type=sa.DATE(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_submission', schema=None) as batch_op:
        batch_op.alter_column('submission_date',
               existing_type=sa.Time(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
