"""empty message

Revision ID: b0ef92b8e9a0
Revises: 7e41afb458c9
Create Date: 2023-11-15 13:31:07.604092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ef92b8e9a0'
down_revision = '7e41afb458c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_submission', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
