"""empty message

Revision ID: fac132c0681d
Revises: 14a6da595d64
Create Date: 2023-11-16 21:26:30.073298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac132c0681d'
down_revision = '14a6da595d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_code', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
